name: Release on NPM
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.1
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "lts"
          registry-url: "https://registry.npmjs.org"
      - name: Build and publish on NPM
        run: |
          deno task build-npm
          cd npm
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
